// ── the console's browser_* tools must speak the SHIPPED server's language ───
//
// `browser_*` is the one tool family the gateway TRANSLATES rather than relays to
// the device: `mcp-browser.ts` maps the console's name to playwright-mcp's and
// forwards the arguments VERBATIM (only `element_ref` is rewritten, and `run_id`
// is lifted out). So a parameter name that does not exist in the shipped
// playwright-mcp is not a cosmetic drift — the argument is dropped or rejected,
// and the console is advertising a call it cannot make.
//
// TWO WERE WRONG, verified against the bundle the agent itself installs
// (`agent/deploy/vale-playwright.zip`, `@playwright/mcp` 0.0.79):
//   * `browser_wait` advertised `condition` — REQUIRED — and `timeout_s`. The
//     server's `browser_wait_for` takes `time`, `text`, `textGone`; there is no
//     `condition` at all. A schema-validating client could only issue a call
//     whose only required argument the server does not have.
//   * `browser_screenshot` advertised `full_page`; the server takes `fullPage`.
//     A full-page request was silently dropped.
//
// WHY NOTHING CAUGHT IT: the parameter-name contract tests compare the gateway
// against the DEVICE (`spec-tools.json`) — but these tools are bridge-routed and
// never reach the device's registry. And `mcp-browser.test.mjs` verified only
// `browser_open -> browser_navigate`; the other six mappings were pinned by
// nothing. A test on a copy can only compare copies; this one compares the
// console against the bundle, which is the third party in the contract.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const ZIP = new URL("../../agent/deploy/vale-playwright.zip", import.meta.url).pathname;

/** The `@playwright/mcp` version the boxed bundle actually ships, or null when
 *  the bundle is not on this box. */
function shippedMcpVersion() {
  try {
    const pkg = execFileSync(
      "unzip",
      ["-p", ZIP, "playwright/node_modules/@playwright/mcp/package.json"],
      { maxBuffer: 4 * 1024 * 1024 },
    ).toString("utf8");
    return JSON.parse(pkg).version ?? null;
  } catch {
    return null;
  }
}

/**
 * The shipped server's schema text per `browser_*` tool, from the COMMITTED
 * snapshot.
 *
 * WHY A SNAPSHOT. The first version of this test read
 * `agent/deploy/vale-playwright.zip` directly — which is a 31 MB BOXED ARTIFACT
 * AND IS NOT TRACKED BY GIT. It passed on this box and FAILED IN CI, the purest
 * form of "works on my machine". The snapshot is generated by
 * `scripts/extract-playwright-tools.mjs`, names the version it came from, and is
 * what CI can actually see — the same pattern `agent/spec-tools.json` already
 * uses for the device inventory.
 *
 * WHAT IS AND IS NOT CROSS-CHECKED, stated because this comment used to promise a
 * check that DID NOT EXIST. It said "WHEN THE BUNDLE IS PRESENT we also check the
 * snapshot against it, so a stale snapshot fails on any box that has the
 * artifact", and pointed at "the banner below" — while the function that read the
 * bundle was called by NOTHING (added and orphaned in the same commit that
 * replaced its call sites). So the snapshot could go stale in silence, which is
 * the exact failure the snapshot exists to prevent.
 *
 * The VERSION is now really cross-checked whenever the bundle is present: a
 * regenerated bundle at a new `@playwright/mcp` version fails here until the
 * snapshot is regenerated, and a skip PRINTS that it skipped instead of looking
 * like a pass.
 *
 * WHAT IT STILL DOES NOT CHECK, so nobody reads more into it than it says: the
 * schema TEXT. Each entry is a non-contiguous concatenation — a slice of the
 * bundle plus referenced definitions appended from elsewhere in the file — so
 * "does the bundle contain this string" is FALSE for 28 of the 78 tools and a
 * containment check would fail on a correct snapshot. A real text check needs the
 * extractor's own logic; until then the version is the honest half.
 */
const snapshot = (() => {
  const raw = readFileSync(new URL("../playwright-tools.json", import.meta.url), "utf8");
  return JSON.parse(raw.split("\n").filter((l) => !l.startsWith("//")).join("\n"));
})();

function shippedSchemaText() {
  const json = snapshot;
  return { source: json.source, tools: json.tools };
}

/** Whether the shipped schema text declares `param` as an object key. */
function declares(text, param) {
  return new RegExp("(^|[{,\\s])" + param + "\\s*:").test(text);
}

/** THE SNAPSHOT IS NOT STALE — the check the orphaned function was supposed to be.
 *
 * `playwright-tools.json` records the version it came from. A regenerated bundle
 * at a different `@playwright/mcp` version means every schema in the snapshot
 * describes a server that is no longer shipped, and the contract test below would
 * keep validating the console against it in perfect silence.
 *
 * WHEN THE BUNDLE IS ABSENT (CI), THIS SKIPS — LOUDLY. A skip that reads like a
 * pass is how the original comment came to describe a check nobody had written.
 */
test("the snapshot names the version the boxed bundle actually ships", () => {
  const actual = shippedMcpVersion();
  const claimed = snapshot.source;
  if (actual === null) {
    console.log(
      `NOTE: NOT cross-checked against the shipped bundle (absent on this box). ` +
        `The snapshot claims ${claimed}; nothing here verified that. ` +
        `Run the release flow, which has the artifact, to close this.`,
    );
    return;
  }
  assert.equal(
    claimed,
    `@playwright/mcp ${actual}`,
    `the snapshot is STALE: it describes ${claimed} while the boxed bundle ships ` +
      `${actual}. Regenerate with \`node gateway/scripts/extract-playwright-tools.mjs\` ` +
      `and commit the result — until then every contract below validates the console ` +
      `against a server that is not the one we ship.`,
  );
});

test("every argument the console sends a browser tool exists in the shipped server", async () => {
  const { allMcpTools } = await import("../src/mcp-tools.ts");
  const toPm = {
    browser_open: "browser_navigate",
    browser_snapshot: "browser_snapshot",
    browser_screenshot: "browser_take_screenshot",
    browser_click: "browser_click",
    browser_type: "browser_type",
    browser_wait: "browser_wait_for",
    browser_close: "browser_close",
  };
  const { source, tools: blocks } = shippedSchemaText();
  const names = Object.keys(blocks);
  assert.ok(names.length >= 5, `the snapshot holds only ${names.length} tools — regenerate it`);
  // A snapshot that captured nothing would make every assertion below vacuous,
  // so the total is asserted rather than trusted.
  const totalChars = names.reduce((n, k) => n + blocks[k].length, 0);
  assert.ok(totalChars > 200, `the snapshot holds only ${totalChars} chars of schema`);
  // The snapshot names its source version so an upgrade shows up as a diff.
  assert.match(source, /^@playwright\/mcp \d/, `the snapshot does not name its source: ${source}`);

  // Arguments the GATEWAY owns and deliberately does not forward.
  const NOT_FORWARDED = new Set(["device", "run_id"]);
  // Arguments the bridge REWRITES into the server's own name before forwarding
  // (`mcp-browser.ts` turns `element_ref` into `target`). Console-only by
  // design, so they are not drift.
  const TRANSLATED = new Set(["element_ref", "text_gone"]);

  const problems = [];
  for (const tool of allMcpTools()) {
    const pm = toPm[tool.name];
    if (!pm) continue;
    const block = blocks[pm];
    assert.ok(block, `the shipped bundle has no ${pm} — the mapping table in mcp-browser.ts is stale`);
    for (const p of Object.keys(tool.inputSchema.properties || {})) {
      if (NOT_FORWARDED.has(p) || TRANSLATED.has(p)) continue;
      if (!declares(block, p)) problems.push(`${tool.name}.${p} (${source} does not declare it)`);
    }
  }
  assert.deepEqual(
    problems,
    [],
    "the console advertises browser arguments the SHIPPED playwright-mcp does not " +
      `accept, so they are dropped or rejected: ${problems.join(" | ")}`,
  );
});

test("every mapping in the bridge points at a tool the shipped server defines", () => {
  const src = readFileSync(new URL("../src/mcp-browser.ts", import.meta.url), "utf8");
  const { tools: blocks } = shippedSchemaText();
  const table = /const toolMap[^{]*\{([\s\S]*?)\n  \};/.exec(src);
  assert.ok(table, "the mapping table moved — re-point this test rather than deleting it");
  const mappings = [...table[1].matchAll(/(\w+):\s*"(\w+)"/g)].map((m) => [m[1], m[2]]);
  assert.ok(mappings.length >= 7, `only ${mappings.length} mappings parsed`);
  const ghosts = mappings.filter(([, pm]) => !blocks[pm]).map(([g, pm]) => `${g} -> ${pm}`);
  assert.deepEqual(ghosts, [], `the bridge maps to tools the server does not define: ${ghosts.join(", ")}`);
});
