// ── the console's browser_* tools must speak the SHIPPED server's language ───
//
// `browser_*` is the one tool family the gateway TRANSLATES rather than relays to
// the device: `mcp-browser.ts` maps the console's name to playwright-mcp's and
// forwards the arguments VERBATIM (only `element_ref` is rewritten, and `run_id`
// is lifted out). So a parameter name that does not exist in the shipped
// playwright-mcp is not a cosmetic drift — the argument is dropped or rejected,
// and the console is advertising a call it cannot make.
//
// TWO WERE WRONG, verified against the bundle the agent itself installs
// (`agent/deploy/vale-playwright.zip`, `@playwright/mcp` 0.0.79):
//   * `browser_wait` advertised `condition` — REQUIRED — and `timeout_s`. The
//     server's `browser_wait_for` takes `time`, `text`, `textGone`; there is no
//     `condition` at all. A schema-validating client could only issue a call
//     whose only required argument the server does not have.
//   * `browser_screenshot` advertised `full_page`; the server takes `fullPage`.
//     A full-page request was silently dropped.
//
// WHY NOTHING CAUGHT IT: the parameter-name contract tests compare the gateway
// against the DEVICE (`spec-tools.json`) — but these tools are bridge-routed and
// never reach the device's registry. And `mcp-browser.test.mjs` verified only
// `browser_open -> browser_navigate`; the other six mappings were pinned by
// nothing. A test on a copy can only compare copies; this one compares the
// console against the bundle, which is the third party in the contract.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const ZIP = new URL("../../agent/deploy/vale-playwright.zip", import.meta.url).pathname;

/** The shipped playwright-mcp bundle, as text. */
function shippedBundle() {
  return execFileSync("unzip", ["-p", ZIP, "playwright/node_modules/playwright-core/lib/coreBundle.js"], {
    maxBuffer: 64 * 1024 * 1024,
  }).toString("utf8");
}

/**
 * The shipped server's schema text per `browser_*` tool, from the COMMITTED
 * snapshot.
 *
 * WHY A SNAPSHOT. The first version of this test read
 * `agent/deploy/vale-playwright.zip` directly — which is a 31 MB BOXED ARTIFACT
 * AND IS NOT TRACKED BY GIT. It passed on this box and FAILED IN CI, the purest
 * form of "works on my machine". The snapshot is generated by
 * `scripts/extract-playwright-tools.mjs`, names the version it came from, and is
 * what CI can actually see — the same pattern `agent/spec-tools.json` already
 * uses for the device inventory.
 *
 * WHEN THE BUNDLE IS PRESENT we also check the snapshot against it, so a stale
 * snapshot fails on any box that has the artifact (this one, and the release
 * box). In CI that half is skipped and the contract half still runs; the banner
 * below says so rather than letting a skip look like a pass.
 */
function shippedSchemaText() {
  const raw = readFileSync(new URL("../playwright-tools.json", import.meta.url), "utf8");
  const json = JSON.parse(raw.split("\n").filter((l) => !l.startsWith("//")).join("\n"));
  return { source: json.source, tools: json.tools };
}

/** Whether the shipped schema text declares `param` as an object key. */
function declares(text, param) {
  return new RegExp("(^|[{,\\s])" + param + "\\s*:").test(text);
}

test("every argument the console sends a browser tool exists in the shipped server", async () => {
  const { allMcpTools } = await import("../src/mcp-tools.ts");
  const toPm = {
    browser_open: "browser_navigate",
    browser_snapshot: "browser_snapshot",
    browser_screenshot: "browser_take_screenshot",
    browser_click: "browser_click",
    browser_type: "browser_type",
    browser_wait: "browser_wait_for",
    browser_close: "browser_close",
  };
  const { source, tools: blocks } = shippedSchemaText();
  const names = Object.keys(blocks);
  assert.ok(names.length >= 5, `the snapshot holds only ${names.length} tools — regenerate it`);
  // A snapshot that captured nothing would make every assertion below vacuous,
  // so the total is asserted rather than trusted.
  const totalChars = names.reduce((n, k) => n + blocks[k].length, 0);
  assert.ok(totalChars > 200, `the snapshot holds only ${totalChars} chars of schema`);
  // The snapshot names its source version so an upgrade shows up as a diff.
  assert.match(source, /^@playwright\/mcp \d/, `the snapshot does not name its source: ${source}`);

  // Arguments the GATEWAY owns and deliberately does not forward.
  const NOT_FORWARDED = new Set(["device", "run_id"]);
  // Arguments the bridge REWRITES into the server's own name before forwarding
  // (`mcp-browser.ts` turns `element_ref` into `target`). Console-only by
  // design, so they are not drift.
  const TRANSLATED = new Set(["element_ref", "text_gone"]);

  const problems = [];
  for (const tool of allMcpTools()) {
    const pm = toPm[tool.name];
    if (!pm) continue;
    const block = blocks[pm];
    assert.ok(block, `the shipped bundle has no ${pm} — the mapping table in mcp-browser.ts is stale`);
    for (const p of Object.keys(tool.inputSchema.properties || {})) {
      if (NOT_FORWARDED.has(p) || TRANSLATED.has(p)) continue;
      if (!declares(block, p)) problems.push(`${tool.name}.${p} (${source} does not declare it)`);
    }
  }
  assert.deepEqual(
    problems,
    [],
    "the console advertises browser arguments the SHIPPED playwright-mcp does not " +
      `accept, so they are dropped or rejected: ${problems.join(" | ")}`,
  );
});

test("every mapping in the bridge points at a tool the shipped server defines", () => {
  const src = readFileSync(new URL("../src/mcp-browser.ts", import.meta.url), "utf8");
  const { tools: blocks } = shippedSchemaText();
  const table = /const toolMap[^{]*\{([\s\S]*?)\n  \};/.exec(src);
  assert.ok(table, "the mapping table moved — re-point this test rather than deleting it");
  const mappings = [...table[1].matchAll(/(\w+):\s*"(\w+)"/g)].map((m) => [m[1], m[2]]);
  assert.ok(mappings.length >= 7, `only ${mappings.length} mappings parsed`);
  const ghosts = mappings.filter(([, pm]) => !blocks[pm]).map(([g, pm]) => `${g} -> ${pm}`);
  assert.deepEqual(ghosts, [], `the bridge maps to tools the server does not define: ${ghosts.join(", ")}`);
});
