// Vale browser helper - GENERATED by vale-agent (browser_run_script writes
// this file next to the scripts it runs; do not edit, it is overwritten).
// acquireBrowser() is the ONE attach-or-headless decision point so AI
// scripts show live in the desktop Browser panel by default:
//   1. CDP endpoint up AND a watchable (non-desktop) page present ->
//      attach to that page (attached=true). Every action is visible live.
//   2. otherwise -> launch a private headless chromium (attached=false)
//      for batch jobs that must not disturb the watched screen.
// close(): attached -> browser.close() disconnects ONLY this node's CDP
// session (device-verified: the Electron view survives; without it the
// node process hangs forever on the open websocket and the runner times
// out). headless -> closes the private browser (no orphaned trees).
"use strict";
const path = require("path");

function coreOf() {
  const base = path.join(process.env.VALE_PW_DIR || "", "node_modules");
  for (const name of ["playwright-core", "playwright"]) {
    try {
      return require(path.join(base, name));
    } catch (e) { /* try next */ }
  }
  throw new Error("bundled playwright not found under VALE_PW_DIR");
}

function cdpEndpoint() {
  return process.env.VALE_CDP_ENDPOINT || "http://127.0.0.1:9333";
}

async function acquireBrowser(opts) {
  opts = opts || {};
  const { chromium } = coreOf();
  // 1) visible view: attach when a watchable page exists.
  try {
    const browser = await chromium.connectOverCDP(cdpEndpoint(), { timeout: 10000 });
    let view = null;
    try {
      const pages = browser.contexts().flatMap((c) => c.pages());
      view = pages.find((p) => {
        try {
          const u = p.url();
          return !!u && u.indexOf("/desktop/") < 0;
        } catch (e) {
          return false;
        }
      }) || null;
    } catch (e) {
      view = null;
    }
    if (view) {
      return {
        browser: browser,
        page: view,
        attached: true,
        close: async () => { try { await browser.close(); } catch (e) {} },
      };
    }
    try { await browser.close(); } catch (e) {}
  } catch (e) { /* CDP down - fall through to headless */ }
  // 2) fallback: private headless (must not disturb the screen).
  // Lab-device self-signed certs (OpenWrt-style defaults): ignore TLS
  // errors here - without it every self-signed device page fails instantly
  // with ERR_CERT_AUTHORITY_INVALID. Scoped to this private browser only.
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({
    viewport: opts.viewport || { width: 1280, height: 800 },
    ignoreHTTPSErrors: true,
  });
  return {
    browser: browser,
    page: page,
    attached: false,
    close: async () => { try { await browser.close(); } catch (e) {} },
  };
}

module.exports = { acquireBrowser };
